/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.example.config;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(config.class);
        DAO d = context.getBean("dao",DAO.class);
       // d.insert(new Student2("Ayan"));
      //  d.update(new Student2(2,"Kost"));
     /*   d.getStudents().forEach(x->{
            System.out.println(x.toString());
        });*/
     //   System.out.println(d.getStudent(1).toString());
     //   d.Delete(1);
    }
}
